### ISSUE TITLE
Shouldn't `generate_prompt(data_point["instruction"], data_point["input"])` be `generate_prompt(data_point["user"], data_point["input"])`

### ISSUE THREAD

**Issue by uakarsh** [modal-labs/doppel-bot#4]
I was going through the codebase for training `llama2` on Modal, and I saw the option [here](https://github.com/modal-labs/doppel-bot/blob/89bec1d02d5daa8a88464bbf2e7d333de370d49d/src/finetune.py#L133), to train the model only on the `labels`, and I think since we want to mask out the `tokens` which corresponds to the `user` and the `input`, the code mentioned [here](https://github.com/modal-labs/doppel-bot/blob/89bec1d02d5daa8a88464bbf2e7d333de370d49d/src/finetune.py#L134)

should be
```python
user_prompt = generate_prompt(data_point["user"], data_point["input"])
```

instead of 
```python
user_prompt = generate_prompt(data_point["instruction"], data_point["input"])
```

**Comment by kning** [comment]
good catch! ill update it now
